import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import "@/styles/ItsBtn.css";
import "../styles/Quill.css";
import "../styles/Clerk.css";
import Nav from "@/components/main/Nav";
import "../middleware";
import { ThemeProvider } from "@/context/theme-provider";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className="min-h-screen bg-slate-200 dark:bg-gray-900 text-black dark:text-white">
            <Nav />
            <div className="mt-20 flex flex-col items-center">{children}</div>
          </body>
        </ThemeProvider>
      </ClerkProvider>
    </html>
  );
}
