import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import "./globals.css";
import "../styles/Quill.css";
import "../styles/Clerk.css";
import { ThemeProvider } from "@/context/ThemeContext";
import Nav from "@/components/main/Nav";
import "../middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ThemeProvider>
        <html lang="en">
          <body className="min-h-screen bg-slate-200 dark:bg-gray-900 text-black dark:text-white">
            <SignedOut>
              <SignInButton mode="modal" />
            </SignedOut>
            <SignedIn>
              <Nav />
              <div className="flex flex-col items-center mt-3">{children}</div>
            </SignedIn>
          </body>
        </html>
      </ThemeProvider>
    </ClerkProvider>
  );
}
